/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppConfig, Signal, SignalDisplay } from "./utils/types";
import { Viewport } from "./components/wt-canvas-nav/wt-canvas-nav";
export { AppConfig, Signal, SignalDisplay } from "./utils/types";
export { Viewport } from "./components/wt-canvas-nav/wt-canvas-nav";
export namespace Components {
    /**
     * Color selection widget.
     * Displays a small color swatch that, when clicked, opens a dropdown
     * with a palette of preset colors and a fill-opacity slider.
     * Emits a `change` event whenever a color or fill value is modified.
     */
    interface ColorPicker {
        /**
          * The currently selected CSS color string.
          * @default 'red'
         */
        "color": string;
        /**
          * Fill opacity (0 = transparent, 1 = fully opaque).
          * @default 0.5
         */
        "fill": number;
        "hide": () => Promise<void>;
        /**
          * Array of CSS color strings to show in the swatch palette.
          * @default DEFAULT_CONFIG.theme.palette
         */
        "palette": string[];
    }
    interface WtApp {
        /**
          * Clear the current VCD data and all signals.
         */
        "clear": () => Promise<void>;
        /**
          * Export current signal list as formatted JSON.
         */
        "export": () => Promise<string>;
        /**
          * Notify the canvas that the underlying file has been modified externally.
         */
        "fileChanged": () => Promise<void>;
        /**
          * Import signals from a JSON string (e.g. saved workspace).
         */
        "import": (json: string) => Promise<void>;
        /**
          * Load / apply a new configuration object.
         */
        "loadConfig": (config: AppConfig) => Promise<void>;
        /**
          * Parse a VCD file buffer. Populates signal tree and logs info.
         */
        "parse": (data: any) => Promise<void>;
        /**
          * Force a canvas redraw / resize.
         */
        "redraw": () => Promise<void>;
        /**
          * Set machine info (WASM module metadata). All licensing logic has been removed – just stores the machine data.
         */
        "setMachine": (machine: any) => Promise<void>;
    }
    interface WtCanvas {
        /**
          * Clear the active-signal highlight.
         */
        "clearActive": () => Promise<void>;
        /**
          * Application configuration (keyboard, mouse, display settings).
         */
        "config"?: AppConfig;
        /**
          * Remove one or more signals by id.
         */
        "delete": (...signals: Signal[]) => Promise<void>;
        /**
          * Whether the backing waveform file has changed on disk.
          * @default false
         */
        "fileChanged": boolean;
        /**
          * Navigate to the next edge of the active signal.
         */
        "nextEdge": () => Promise<void>;
        /**
          * Navigate to the previous edge of the active signal.
         */
        "prevEdge": () => Promise<void>;
        /**
          * Set the currently-highlighted / active signal.
         */
        "setActiveSignal": (id: number) => Promise<void>;
        /**
          * Map of signal id -> signal metadata, keyed by numeric id.
         */
        "signals": Map<number, Signal> | null;
        /**
          * Re-evaluate cursor values without moving it.
         */
        "updateCursor": () => Promise<void>;
    }
    /**
     * Navigation bar displayed above the waveform canvas.
     * Provides zoom controls (in / out / fit), a reload button,
     * a settings button, and a minimap slider showing the current
     * viewport position within the full waveform.
     */
    interface WtCanvasNav {
        /**
          * Whether the backing file has changed on disk (highlights the reload button).
          * @default false
         */
        "fileChanged": boolean;
        /**
          * Position the primary cursor marker at the given percentage (0-100).
         */
        "setPrimaryMarker": (pct: number) => Promise<void>;
        /**
          * Update the viewport data and refresh the minimap preview.
         */
        "setViewport": (vp: Viewport) => Promise<void>;
    }
    /**
     * Properties panel shown below the sidebar.
     * Displays and edits shared display properties for the currently
     * selected signal(s): color, fill, renderer mode, endianness, radix,
     * and waveform height.
     */
    interface WtProperties {
        /**
          * The set of currently selected signals whose properties are shown/edited.
          * @default []
         */
        "signals": Signal[];
    }
    /**
     * Modal dialog for browsing and adding VCD signals to the waveform display.
     * Shows a hierarchical module tree on the left and a filterable signal list
     * on the right.  Supports multi-select (ctrl/shift), keyboard navigation,
     * and type-based filtering (wire, reg, logic, etc.).
     */
    interface WtSearch {
        /**
          * Hide the search dialog.
         */
        "hide": () => Promise<void>;
        /**
          * Load a signal dictionary from the parsed VCD file.
         */
        "load": (dict: any[]) => Promise<void>;
        /**
          * Horizontal offset for positioning.
          * @default 0
         */
        "offsetX": number;
        /**
          * Show the search dialog.
         */
        "show": () => Promise<void>;
        /**
          * Toggle the search dialog visibility.
         */
        "toggle": () => Promise<void>;
    }
    /**
     * Settings panel component.
     * Provides tabbed UI for:
     *  - Keyboard shortcut customisation
     *  - Advanced / JSON config editing
     *  - About page (rebranded to OpenTrace)
     * All licensing / activation functionality has been removed.
     */
    interface WtSettings {
        /**
          * The application config object (passed by reference from the host).
          * @default null
         */
        "config": AppConfig | null;
        /**
          * Hide the settings window.
         */
        "hide": () => Promise<void>;
        /**
          * Show the settings window.
         */
        "show": () => Promise<void>;
    }
    /**
     * Main sidebar container for the signal list.
     * Manages:
     *  - Rendering the ordered list of signals via `wt-sidebar-item`.
     *  - Multi-select with Ctrl click, adjacent navigation with arrows.
     *  - Drag-and-drop reordering of signals.
     *  - A footer with "Add Signals" and delete buttons.
     *  - Delegates to `wt-properties` for bulk property editing.
     */
    interface WtSidebar {
        /**
          * Clear all selection state.
         */
        "clearSelection": () => Promise<void>;
        /**
          * Whether the waveform definition file has been fully parsed.
          * @default false
         */
        "defined": boolean;
        /**
          * Whether there was an error loading the file.
          * @default false
         */
        "error": boolean;
        /**
          * Return selected signal IDs and clear the selection classes.
         */
        "getSelected": () => Promise<number[]>;
        /**
          * Move selected signals up or down in the list.
         */
        "moveSelectedSignals": (direction?: number) => Promise<void>;
        /**
          * Recalculate signal positions after layout changes.
         */
        "resize": () => Promise<boolean>;
        /**
          * Select the next or previous adjacent signal.
         */
        "selectAdjacent": (forward?: boolean) => Promise<void>;
        /**
          * Select all signals.
         */
        "selectAll": () => Promise<void>;
        /**
          * @default []
         */
        "signals": Signal[];
        /**
          * Update cursor values for all visible signals.
         */
        "updateCursor": (values: Record<string, string>) => Promise<void>;
    }
    /**
     * Renders a single signal row inside the sidebar.
     * For **group** signals it shows a group header with an editable alias
     * and recursively renders children as nested `wt-sidebar-item` elements.
     * For **divider** signals it renders a blank header.
     * For all other types it renders the icon, optional bus-size badge,
     * signal name (with scope), and the current value display.
     */
    interface WtSidebarItem {
        /**
          * Measure the rendered element and write display.y / display.height back.
         */
        "resizeSignal": () => Promise<void>;
        /**
          * The signal data object to render.
         */
        "signal": Signal;
        /**
          * Current cursor value for this signal (displayed in the radix column).
          * @default ''
         */
        "value": string;
    }
    /**
     * Scrollable, drag-reorderable signal list container.
     * This is a lightweight generic drag-and-drop list used for
     * prototyping reorder behaviour.  The main sidebar (`wt-sidebar`)
     * has its own built-in drag logic that supersedes this component for
     * the primary signal list, but `wt-sidebar-list` is retained as a
     * reusable primitive.
     */
    interface WtSidebarList {
        /**
          * Signal items to display. The setter copies the reference and triggers a re-render.
          * @default []
         */
        "signals": Signal[];
    }
    /**
     * Inline property editor for a single signal.
     * Displays a color picker, renderer-type toggle buttons
     * (digital / step / linear), and a format button.
     * Emits `waveformChanged` when any property is modified so the
     * parent can update the canvas.
     */
    interface WtSidebarProp {
        /**
          * Bit-width of the signal (controls which renderer buttons are shown).
          * @default 0
         */
        "busSize": number;
        /**
          * Display options for the signal being edited.
          * @default {} as SignalDisplay
         */
        "options": SignalDisplay;
    }
    /**
     * Dropdown menu for selecting the display radix of a signal value.
     * Lists all `Radix` members (bin, oct, hex, unsigned, signed, ascii,
     * utf8, float) and highlights the currently-selected one.
     * Emits `waveformChanged` on selection and `select` to let the
     * parent know a choice was made (so it can close the dropdown).
     */
    interface WtSidebarRadix {
        /**
          * Display options (contains `.radix` and `.color`).
          * @default {} as SignalDisplay
         */
        "options": SignalDisplay;
    }
    interface WtWindow {
        /**
          * When true, applies a backdrop blur effect behind the window.
          * @default false
         */
        "backgroundBlur": boolean;
        /**
          * Hide the window and deselect any machine-list entries.
         */
        "hide": () => Promise<void>;
        /**
          * Show the window.
         */
        "show": () => Promise<void>;
        /**
          * Controls visibility of the modal overlay.
          * @default false
         */
        "visible": boolean;
        /**
          * Title displayed in the gradient title bar. Empty string hides the bar.
          * @default ''
         */
        "windowTitle": string;
    }
}
export interface ColorPickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLColorPickerElement;
}
export interface WtAppCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtAppElement;
}
export interface WtCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtCanvasElement;
}
export interface WtCanvasNavCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtCanvasNavElement;
}
export interface WtPropertiesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtPropertiesElement;
}
export interface WtSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtSearchElement;
}
export interface WtSettingsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtSettingsElement;
}
export interface WtSidebarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtSidebarElement;
}
export interface WtSidebarItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtSidebarItemElement;
}
export interface WtSidebarPropCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtSidebarPropElement;
}
export interface WtSidebarRadixCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWtSidebarRadixElement;
}
declare global {
    interface HTMLColorPickerElementEventMap {
        "change": { color: string; fill: number };
    }
    /**
     * Color selection widget.
     * Displays a small color swatch that, when clicked, opens a dropdown
     * with a palette of preset colors and a fill-opacity slider.
     * Emits a `change` event whenever a color or fill value is modified.
     */
    interface HTMLColorPickerElement extends Components.ColorPicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLColorPickerElementEventMap>(type: K, listener: (this: HTMLColorPickerElement, ev: ColorPickerCustomEvent<HTMLColorPickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLColorPickerElementEventMap>(type: K, listener: (this: HTMLColorPickerElement, ev: ColorPickerCustomEvent<HTMLColorPickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLColorPickerElement: {
        prototype: HTMLColorPickerElement;
        new (): HTMLColorPickerElement;
    };
    interface HTMLWtAppElementEventMap {
        "vcd-ready": void;
        "vcd-done": void;
        "log": string;
        "file-reload": {};
        "config-save": string;
        "config-reset": {};
        "config-reload": {};
        "settings-json": {};
        "open-website": {};
    }
    interface HTMLWtAppElement extends Components.WtApp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtAppElementEventMap>(type: K, listener: (this: HTMLWtAppElement, ev: WtAppCustomEvent<HTMLWtAppElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtAppElementEventMap>(type: K, listener: (this: HTMLWtAppElement, ev: WtAppCustomEvent<HTMLWtAppElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtAppElement: {
        prototype: HTMLWtAppElement;
        new (): HTMLWtAppElement;
    };
    interface HTMLWtCanvasElementEventMap {
        "setCursor": Record<string, string>;
        "settings": void;
    }
    interface HTMLWtCanvasElement extends Components.WtCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtCanvasElementEventMap>(type: K, listener: (this: HTMLWtCanvasElement, ev: WtCanvasCustomEvent<HTMLWtCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtCanvasElementEventMap>(type: K, listener: (this: HTMLWtCanvasElement, ev: WtCanvasCustomEvent<HTMLWtCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtCanvasElement: {
        prototype: HTMLWtCanvasElement;
        new (): HTMLWtCanvasElement;
    };
    interface HTMLWtCanvasNavElementEventMap {
        "change": { cmd: string; value?: number };
        "file-reload": {};
        "settings": {};
    }
    /**
     * Navigation bar displayed above the waveform canvas.
     * Provides zoom controls (in / out / fit), a reload button,
     * a settings button, and a minimap slider showing the current
     * viewport position within the full waveform.
     */
    interface HTMLWtCanvasNavElement extends Components.WtCanvasNav, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtCanvasNavElementEventMap>(type: K, listener: (this: HTMLWtCanvasNavElement, ev: WtCanvasNavCustomEvent<HTMLWtCanvasNavElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtCanvasNavElementEventMap>(type: K, listener: (this: HTMLWtCanvasNavElement, ev: WtCanvasNavCustomEvent<HTMLWtCanvasNavElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtCanvasNavElement: {
        prototype: HTMLWtCanvasNavElement;
        new (): HTMLWtCanvasNavElement;
    };
    interface HTMLWtPropertiesElementEventMap {
        "redraw": { resize: boolean };
    }
    /**
     * Properties panel shown below the sidebar.
     * Displays and edits shared display properties for the currently
     * selected signal(s): color, fill, renderer mode, endianness, radix,
     * and waveform height.
     */
    interface HTMLWtPropertiesElement extends Components.WtProperties, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtPropertiesElementEventMap>(type: K, listener: (this: HTMLWtPropertiesElement, ev: WtPropertiesCustomEvent<HTMLWtPropertiesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtPropertiesElementEventMap>(type: K, listener: (this: HTMLWtPropertiesElement, ev: WtPropertiesCustomEvent<HTMLWtPropertiesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtPropertiesElement: {
        prototype: HTMLWtPropertiesElement;
        new (): HTMLWtPropertiesElement;
    };
    interface HTMLWtSearchElementEventMap {
        "add": Signal[];
    }
    /**
     * Modal dialog for browsing and adding VCD signals to the waveform display.
     * Shows a hierarchical module tree on the left and a filterable signal list
     * on the right.  Supports multi-select (ctrl/shift), keyboard navigation,
     * and type-based filtering (wire, reg, logic, etc.).
     */
    interface HTMLWtSearchElement extends Components.WtSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtSearchElementEventMap>(type: K, listener: (this: HTMLWtSearchElement, ev: WtSearchCustomEvent<HTMLWtSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtSearchElementEventMap>(type: K, listener: (this: HTMLWtSearchElement, ev: WtSearchCustomEvent<HTMLWtSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtSearchElement: {
        prototype: HTMLWtSearchElement;
        new (): HTMLWtSearchElement;
    };
    interface HTMLWtSettingsElementEventMap {
        "config-save": string;
        "settings-json": {};
        "config-reload": {};
        "config-reset": {};
    }
    /**
     * Settings panel component.
     * Provides tabbed UI for:
     *  - Keyboard shortcut customisation
     *  - Advanced / JSON config editing
     *  - About page (rebranded to OpenTrace)
     * All licensing / activation functionality has been removed.
     */
    interface HTMLWtSettingsElement extends Components.WtSettings, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtSettingsElementEventMap>(type: K, listener: (this: HTMLWtSettingsElement, ev: WtSettingsCustomEvent<HTMLWtSettingsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtSettingsElementEventMap>(type: K, listener: (this: HTMLWtSettingsElement, ev: WtSettingsCustomEvent<HTMLWtSettingsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtSettingsElement: {
        prototype: HTMLWtSettingsElement;
        new (): HTMLWtSettingsElement;
    };
    interface HTMLWtSidebarElementEventMap {
        "add": void;
        "delete": void;
        "waveformChanged": void;
        "redraw": { resize?: boolean };
        "setActiveSignal": number;
    }
    /**
     * Main sidebar container for the signal list.
     * Manages:
     *  - Rendering the ordered list of signals via `wt-sidebar-item`.
     *  - Multi-select with Ctrl click, adjacent navigation with arrows.
     *  - Drag-and-drop reordering of signals.
     *  - A footer with "Add Signals" and delete buttons.
     *  - Delegates to `wt-properties` for bulk property editing.
     */
    interface HTMLWtSidebarElement extends Components.WtSidebar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtSidebarElementEventMap>(type: K, listener: (this: HTMLWtSidebarElement, ev: WtSidebarCustomEvent<HTMLWtSidebarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtSidebarElementEventMap>(type: K, listener: (this: HTMLWtSidebarElement, ev: WtSidebarCustomEvent<HTMLWtSidebarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtSidebarElement: {
        prototype: HTMLWtSidebarElement;
        new (): HTMLWtSidebarElement;
    };
    interface HTMLWtSidebarItemElementEventMap {
        "resizeSignals": void;
    }
    /**
     * Renders a single signal row inside the sidebar.
     * For **group** signals it shows a group header with an editable alias
     * and recursively renders children as nested `wt-sidebar-item` elements.
     * For **divider** signals it renders a blank header.
     * For all other types it renders the icon, optional bus-size badge,
     * signal name (with scope), and the current value display.
     */
    interface HTMLWtSidebarItemElement extends Components.WtSidebarItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtSidebarItemElementEventMap>(type: K, listener: (this: HTMLWtSidebarItemElement, ev: WtSidebarItemCustomEvent<HTMLWtSidebarItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtSidebarItemElementEventMap>(type: K, listener: (this: HTMLWtSidebarItemElement, ev: WtSidebarItemCustomEvent<HTMLWtSidebarItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtSidebarItemElement: {
        prototype: HTMLWtSidebarItemElement;
        new (): HTMLWtSidebarItemElement;
    };
    /**
     * Scrollable, drag-reorderable signal list container.
     * This is a lightweight generic drag-and-drop list used for
     * prototyping reorder behaviour.  The main sidebar (`wt-sidebar`)
     * has its own built-in drag logic that supersedes this component for
     * the primary signal list, but `wt-sidebar-list` is retained as a
     * reusable primitive.
     */
    interface HTMLWtSidebarListElement extends Components.WtSidebarList, HTMLStencilElement {
    }
    var HTMLWtSidebarListElement: {
        prototype: HTMLWtSidebarListElement;
        new (): HTMLWtSidebarListElement;
    };
    interface HTMLWtSidebarPropElementEventMap {
        "waveformChanged": SignalDisplay;
        "resizeSignals": void;
    }
    /**
     * Inline property editor for a single signal.
     * Displays a color picker, renderer-type toggle buttons
     * (digital / step / linear), and a format button.
     * Emits `waveformChanged` when any property is modified so the
     * parent can update the canvas.
     */
    interface HTMLWtSidebarPropElement extends Components.WtSidebarProp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtSidebarPropElementEventMap>(type: K, listener: (this: HTMLWtSidebarPropElement, ev: WtSidebarPropCustomEvent<HTMLWtSidebarPropElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtSidebarPropElementEventMap>(type: K, listener: (this: HTMLWtSidebarPropElement, ev: WtSidebarPropCustomEvent<HTMLWtSidebarPropElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtSidebarPropElement: {
        prototype: HTMLWtSidebarPropElement;
        new (): HTMLWtSidebarPropElement;
    };
    interface HTMLWtSidebarRadixElementEventMap {
        "waveformChanged": SignalDisplay;
        "select": void;
        "resizeSignals": void;
    }
    /**
     * Dropdown menu for selecting the display radix of a signal value.
     * Lists all `Radix` members (bin, oct, hex, unsigned, signed, ascii,
     * utf8, float) and highlights the currently-selected one.
     * Emits `waveformChanged` on selection and `select` to let the
     * parent know a choice was made (so it can close the dropdown).
     */
    interface HTMLWtSidebarRadixElement extends Components.WtSidebarRadix, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWtSidebarRadixElementEventMap>(type: K, listener: (this: HTMLWtSidebarRadixElement, ev: WtSidebarRadixCustomEvent<HTMLWtSidebarRadixElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWtSidebarRadixElementEventMap>(type: K, listener: (this: HTMLWtSidebarRadixElement, ev: WtSidebarRadixCustomEvent<HTMLWtSidebarRadixElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWtSidebarRadixElement: {
        prototype: HTMLWtSidebarRadixElement;
        new (): HTMLWtSidebarRadixElement;
    };
    interface HTMLWtWindowElement extends Components.WtWindow, HTMLStencilElement {
    }
    var HTMLWtWindowElement: {
        prototype: HTMLWtWindowElement;
        new (): HTMLWtWindowElement;
    };
    interface HTMLElementTagNameMap {
        "color-picker": HTMLColorPickerElement;
        "wt-app": HTMLWtAppElement;
        "wt-canvas": HTMLWtCanvasElement;
        "wt-canvas-nav": HTMLWtCanvasNavElement;
        "wt-properties": HTMLWtPropertiesElement;
        "wt-search": HTMLWtSearchElement;
        "wt-settings": HTMLWtSettingsElement;
        "wt-sidebar": HTMLWtSidebarElement;
        "wt-sidebar-item": HTMLWtSidebarItemElement;
        "wt-sidebar-list": HTMLWtSidebarListElement;
        "wt-sidebar-prop": HTMLWtSidebarPropElement;
        "wt-sidebar-radix": HTMLWtSidebarRadixElement;
        "wt-window": HTMLWtWindowElement;
    }
}
declare namespace LocalJSX {
    /**
     * Color selection widget.
     * Displays a small color swatch that, when clicked, opens a dropdown
     * with a palette of preset colors and a fill-opacity slider.
     * Emits a `change` event whenever a color or fill value is modified.
     */
    interface ColorPicker {
        /**
          * The currently selected CSS color string.
          * @default 'red'
         */
        "color"?: string;
        /**
          * Fill opacity (0 = transparent, 1 = fully opaque).
          * @default 0.5
         */
        "fill"?: number;
        /**
          * Emitted when the user selects a new color or changes the fill.
         */
        "onChange"?: (event: ColorPickerCustomEvent<{ color: string; fill: number }>) => void;
        /**
          * Array of CSS color strings to show in the swatch palette.
          * @default DEFAULT_CONFIG.theme.palette
         */
        "palette"?: string[];
    }
    interface WtApp {
        "onConfig-reload"?: (event: WtAppCustomEvent<{}>) => void;
        "onConfig-reset"?: (event: WtAppCustomEvent<{}>) => void;
        "onConfig-save"?: (event: WtAppCustomEvent<string>) => void;
        "onFile-reload"?: (event: WtAppCustomEvent<{}>) => void;
        "onLog"?: (event: WtAppCustomEvent<string>) => void;
        "onOpen-website"?: (event: WtAppCustomEvent<{}>) => void;
        "onSettings-json"?: (event: WtAppCustomEvent<{}>) => void;
        "onVcd-done"?: (event: WtAppCustomEvent<void>) => void;
        "onVcd-ready"?: (event: WtAppCustomEvent<void>) => void;
    }
    interface WtCanvas {
        /**
          * Application configuration (keyboard, mouse, display settings).
         */
        "config"?: AppConfig;
        /**
          * Whether the backing waveform file has changed on disk.
          * @default false
         */
        "fileChanged"?: boolean;
        /**
          * Emitted when the cursor moves, carrying the value at the cursor for each signal.
         */
        "onSetCursor"?: (event: WtCanvasCustomEvent<Record<string, string>>) => void;
        /**
          * Emitted when the user requests the settings panel.
         */
        "onSettings"?: (event: WtCanvasCustomEvent<void>) => void;
        /**
          * Map of signal id -> signal metadata, keyed by numeric id.
         */
        "signals": Map<number, Signal> | null;
    }
    /**
     * Navigation bar displayed above the waveform canvas.
     * Provides zoom controls (in / out / fit), a reload button,
     * a settings button, and a minimap slider showing the current
     * viewport position within the full waveform.
     */
    interface WtCanvasNav {
        /**
          * Whether the backing file has changed on disk (highlights the reload button).
          * @default false
         */
        "fileChanged"?: boolean;
        /**
          * Emitted when the user requests a viewport change (zoom, goto).
         */
        "onChange"?: (event: WtCanvasNavCustomEvent<{ cmd: string; value?: number }>) => void;
        /**
          * Emitted when the user clicks the reload button.
         */
        "onFile-reload"?: (event: WtCanvasNavCustomEvent<{}>) => void;
        /**
          * Emitted when the user clicks the settings button.
         */
        "onSettings"?: (event: WtCanvasNavCustomEvent<{}>) => void;
    }
    /**
     * Properties panel shown below the sidebar.
     * Displays and edits shared display properties for the currently
     * selected signal(s): color, fill, renderer mode, endianness, radix,
     * and waveform height.
     */
    interface WtProperties {
        /**
          * Emitted when a property changes, requesting the canvas to redraw.
         */
        "onRedraw"?: (event: WtPropertiesCustomEvent<{ resize: boolean }>) => void;
        /**
          * The set of currently selected signals whose properties are shown/edited.
          * @default []
         */
        "signals"?: Signal[];
    }
    /**
     * Modal dialog for browsing and adding VCD signals to the waveform display.
     * Shows a hierarchical module tree on the left and a filterable signal list
     * on the right.  Supports multi-select (ctrl/shift), keyboard navigation,
     * and type-based filtering (wire, reg, logic, etc.).
     */
    interface WtSearch {
        /**
          * Horizontal offset for positioning.
          * @default 0
         */
        "offsetX"?: number;
        /**
          * Emitted when the user adds selected signals. Detail is the array of Signal objects.
         */
        "onAdd"?: (event: WtSearchCustomEvent<Signal[]>) => void;
    }
    /**
     * Settings panel component.
     * Provides tabbed UI for:
     *  - Keyboard shortcut customisation
     *  - Advanced / JSON config editing
     *  - About page (rebranded to OpenTrace)
     * All licensing / activation functionality has been removed.
     */
    interface WtSettings {
        /**
          * The application config object (passed by reference from the host).
          * @default null
         */
        "config"?: AppConfig | null;
        /**
          * Emitted to request the host to reload config from disk.
         */
        "onConfig-reload"?: (event: WtSettingsCustomEvent<{}>) => void;
        /**
          * Emitted to request the host to reset config to defaults.
         */
        "onConfig-reset"?: (event: WtSettingsCustomEvent<{}>) => void;
        /**
          * Emitted when the user clicks Apply to persist shortcut changes.
         */
        "onConfig-save"?: (event: WtSettingsCustomEvent<string>) => void;
        /**
          * Emitted to request the host to open the JSON settings file.
         */
        "onSettings-json"?: (event: WtSettingsCustomEvent<{}>) => void;
    }
    /**
     * Main sidebar container for the signal list.
     * Manages:
     *  - Rendering the ordered list of signals via `wt-sidebar-item`.
     *  - Multi-select with Ctrl click, adjacent navigation with arrows.
     *  - Drag-and-drop reordering of signals.
     *  - A footer with "Add Signals" and delete buttons.
     *  - Delegates to `wt-properties` for bulk property editing.
     */
    interface WtSidebar {
        /**
          * Whether the waveform definition file has been fully parsed.
          * @default false
         */
        "defined"?: boolean;
        /**
          * Whether there was an error loading the file.
          * @default false
         */
        "error"?: boolean;
        /**
          * Emitted when the user clicks "Add Signals".
         */
        "onAdd"?: (event: WtSidebarCustomEvent<void>) => void;
        /**
          * Emitted when the user clicks the delete button.
         */
        "onDelete"?: (event: WtSidebarCustomEvent<void>) => void;
        /**
          * Emitted when the sidebar layout changes and the canvas needs a redraw.
         */
        "onRedraw"?: (event: WtSidebarCustomEvent<{ resize?: boolean }>) => void;
        /**
          * Emitted to tell the canvas which signal to highlight.
         */
        "onSetActiveSignal"?: (event: WtSidebarCustomEvent<number>) => void;
        /**
          * Emitted when signals are reordered, properties change, etc.
         */
        "onWaveformChanged"?: (event: WtSidebarCustomEvent<void>) => void;
        /**
          * @default []
         */
        "signals"?: Signal[];
    }
    /**
     * Renders a single signal row inside the sidebar.
     * For **group** signals it shows a group header with an editable alias
     * and recursively renders children as nested `wt-sidebar-item` elements.
     * For **divider** signals it renders a blank header.
     * For all other types it renders the icon, optional bus-size badge,
     * signal name (with scope), and the current value display.
     */
    interface WtSidebarItem {
        /**
          * Bubbles up to request a full signal-height recalculation.
         */
        "onResizeSignals"?: (event: WtSidebarItemCustomEvent<void>) => void;
        /**
          * The signal data object to render.
         */
        "signal": Signal;
        /**
          * Current cursor value for this signal (displayed in the radix column).
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Scrollable, drag-reorderable signal list container.
     * This is a lightweight generic drag-and-drop list used for
     * prototyping reorder behaviour.  The main sidebar (`wt-sidebar`)
     * has its own built-in drag logic that supersedes this component for
     * the primary signal list, but `wt-sidebar-list` is retained as a
     * reusable primitive.
     */
    interface WtSidebarList {
        /**
          * Signal items to display. The setter copies the reference and triggers a re-render.
          * @default []
         */
        "signals"?: Signal[];
    }
    /**
     * Inline property editor for a single signal.
     * Displays a color picker, renderer-type toggle buttons
     * (digital / step / linear), and a format button.
     * Emits `waveformChanged` when any property is modified so the
     * parent can update the canvas.
     */
    interface WtSidebarProp {
        /**
          * Bit-width of the signal (controls which renderer buttons are shown).
          * @default 0
         */
        "busSize"?: number;
        /**
          * Requests a full signal-height recalculation.
         */
        "onResizeSignals"?: (event: WtSidebarPropCustomEvent<void>) => void;
        /**
          * Emitted whenever a display property is changed.
         */
        "onWaveformChanged"?: (event: WtSidebarPropCustomEvent<SignalDisplay>) => void;
        /**
          * Display options for the signal being edited.
          * @default {} as SignalDisplay
         */
        "options"?: SignalDisplay;
    }
    /**
     * Dropdown menu for selecting the display radix of a signal value.
     * Lists all `Radix` members (bin, oct, hex, unsigned, signed, ascii,
     * utf8, float) and highlights the currently-selected one.
     * Emits `waveformChanged` on selection and `select` to let the
     * parent know a choice was made (so it can close the dropdown).
     */
    interface WtSidebarRadix {
        /**
          * Requests a full signal-height recalculation.
         */
        "onResizeSignals"?: (event: WtSidebarRadixCustomEvent<void>) => void;
        /**
          * Emitted after a radix is selected (used by parent to close the menu).
         */
        "onSelect"?: (event: WtSidebarRadixCustomEvent<void>) => void;
        /**
          * Emitted when the radix changes.
         */
        "onWaveformChanged"?: (event: WtSidebarRadixCustomEvent<SignalDisplay>) => void;
        /**
          * Display options (contains `.radix` and `.color`).
          * @default {} as SignalDisplay
         */
        "options"?: SignalDisplay;
    }
    interface WtWindow {
        /**
          * When true, applies a backdrop blur effect behind the window.
          * @default false
         */
        "backgroundBlur"?: boolean;
        /**
          * Controls visibility of the modal overlay.
          * @default false
         */
        "visible"?: boolean;
        /**
          * Title displayed in the gradient title bar. Empty string hides the bar.
          * @default ''
         */
        "windowTitle"?: string;
    }

    interface ColorPickerAttributes {
        "color": string;
        "fill": number;
    }
    interface WtCanvasAttributes {
        "fileChanged": boolean;
    }
    interface WtCanvasNavAttributes {
        "fileChanged": boolean;
    }
    interface WtSearchAttributes {
        "offsetX": number;
    }
    interface WtSidebarAttributes {
        "defined": boolean;
        "error": boolean;
    }
    interface WtSidebarItemAttributes {
        "value": string;
    }
    interface WtSidebarPropAttributes {
        "busSize": number;
    }
    interface WtWindowAttributes {
        "windowTitle": string;
        "backgroundBlur": boolean;
        "visible": boolean;
    }

    interface IntrinsicElements {
        "color-picker": Omit<ColorPicker, keyof ColorPickerAttributes> & { [K in keyof ColorPicker & keyof ColorPickerAttributes]?: ColorPicker[K] } & { [K in keyof ColorPicker & keyof ColorPickerAttributes as `attr:${K}`]?: ColorPickerAttributes[K] } & { [K in keyof ColorPicker & keyof ColorPickerAttributes as `prop:${K}`]?: ColorPicker[K] };
        "wt-app": WtApp;
        "wt-canvas": Omit<WtCanvas, keyof WtCanvasAttributes> & { [K in keyof WtCanvas & keyof WtCanvasAttributes]?: WtCanvas[K] } & { [K in keyof WtCanvas & keyof WtCanvasAttributes as `attr:${K}`]?: WtCanvasAttributes[K] } & { [K in keyof WtCanvas & keyof WtCanvasAttributes as `prop:${K}`]?: WtCanvas[K] };
        "wt-canvas-nav": Omit<WtCanvasNav, keyof WtCanvasNavAttributes> & { [K in keyof WtCanvasNav & keyof WtCanvasNavAttributes]?: WtCanvasNav[K] } & { [K in keyof WtCanvasNav & keyof WtCanvasNavAttributes as `attr:${K}`]?: WtCanvasNavAttributes[K] } & { [K in keyof WtCanvasNav & keyof WtCanvasNavAttributes as `prop:${K}`]?: WtCanvasNav[K] };
        "wt-properties": WtProperties;
        "wt-search": Omit<WtSearch, keyof WtSearchAttributes> & { [K in keyof WtSearch & keyof WtSearchAttributes]?: WtSearch[K] } & { [K in keyof WtSearch & keyof WtSearchAttributes as `attr:${K}`]?: WtSearchAttributes[K] } & { [K in keyof WtSearch & keyof WtSearchAttributes as `prop:${K}`]?: WtSearch[K] };
        "wt-settings": WtSettings;
        "wt-sidebar": Omit<WtSidebar, keyof WtSidebarAttributes> & { [K in keyof WtSidebar & keyof WtSidebarAttributes]?: WtSidebar[K] } & { [K in keyof WtSidebar & keyof WtSidebarAttributes as `attr:${K}`]?: WtSidebarAttributes[K] } & { [K in keyof WtSidebar & keyof WtSidebarAttributes as `prop:${K}`]?: WtSidebar[K] };
        "wt-sidebar-item": Omit<WtSidebarItem, keyof WtSidebarItemAttributes> & { [K in keyof WtSidebarItem & keyof WtSidebarItemAttributes]?: WtSidebarItem[K] } & { [K in keyof WtSidebarItem & keyof WtSidebarItemAttributes as `attr:${K}`]?: WtSidebarItemAttributes[K] } & { [K in keyof WtSidebarItem & keyof WtSidebarItemAttributes as `prop:${K}`]?: WtSidebarItem[K] };
        "wt-sidebar-list": WtSidebarList;
        "wt-sidebar-prop": Omit<WtSidebarProp, keyof WtSidebarPropAttributes> & { [K in keyof WtSidebarProp & keyof WtSidebarPropAttributes]?: WtSidebarProp[K] } & { [K in keyof WtSidebarProp & keyof WtSidebarPropAttributes as `attr:${K}`]?: WtSidebarPropAttributes[K] } & { [K in keyof WtSidebarProp & keyof WtSidebarPropAttributes as `prop:${K}`]?: WtSidebarProp[K] };
        "wt-sidebar-radix": WtSidebarRadix;
        "wt-window": Omit<WtWindow, keyof WtWindowAttributes> & { [K in keyof WtWindow & keyof WtWindowAttributes]?: WtWindow[K] } & { [K in keyof WtWindow & keyof WtWindowAttributes as `attr:${K}`]?: WtWindowAttributes[K] } & { [K in keyof WtWindow & keyof WtWindowAttributes as `prop:${K}`]?: WtWindow[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Color selection widget.
             * Displays a small color swatch that, when clicked, opens a dropdown
             * with a palette of preset colors and a fill-opacity slider.
             * Emits a `change` event whenever a color or fill value is modified.
             */
            "color-picker": LocalJSX.IntrinsicElements["color-picker"] & JSXBase.HTMLAttributes<HTMLColorPickerElement>;
            "wt-app": LocalJSX.IntrinsicElements["wt-app"] & JSXBase.HTMLAttributes<HTMLWtAppElement>;
            "wt-canvas": LocalJSX.IntrinsicElements["wt-canvas"] & JSXBase.HTMLAttributes<HTMLWtCanvasElement>;
            /**
             * Navigation bar displayed above the waveform canvas.
             * Provides zoom controls (in / out / fit), a reload button,
             * a settings button, and a minimap slider showing the current
             * viewport position within the full waveform.
             */
            "wt-canvas-nav": LocalJSX.IntrinsicElements["wt-canvas-nav"] & JSXBase.HTMLAttributes<HTMLWtCanvasNavElement>;
            /**
             * Properties panel shown below the sidebar.
             * Displays and edits shared display properties for the currently
             * selected signal(s): color, fill, renderer mode, endianness, radix,
             * and waveform height.
             */
            "wt-properties": LocalJSX.IntrinsicElements["wt-properties"] & JSXBase.HTMLAttributes<HTMLWtPropertiesElement>;
            /**
             * Modal dialog for browsing and adding VCD signals to the waveform display.
             * Shows a hierarchical module tree on the left and a filterable signal list
             * on the right.  Supports multi-select (ctrl/shift), keyboard navigation,
             * and type-based filtering (wire, reg, logic, etc.).
             */
            "wt-search": LocalJSX.IntrinsicElements["wt-search"] & JSXBase.HTMLAttributes<HTMLWtSearchElement>;
            /**
             * Settings panel component.
             * Provides tabbed UI for:
             *  - Keyboard shortcut customisation
             *  - Advanced / JSON config editing
             *  - About page (rebranded to OpenTrace)
             * All licensing / activation functionality has been removed.
             */
            "wt-settings": LocalJSX.IntrinsicElements["wt-settings"] & JSXBase.HTMLAttributes<HTMLWtSettingsElement>;
            /**
             * Main sidebar container for the signal list.
             * Manages:
             *  - Rendering the ordered list of signals via `wt-sidebar-item`.
             *  - Multi-select with Ctrl click, adjacent navigation with arrows.
             *  - Drag-and-drop reordering of signals.
             *  - A footer with "Add Signals" and delete buttons.
             *  - Delegates to `wt-properties` for bulk property editing.
             */
            "wt-sidebar": LocalJSX.IntrinsicElements["wt-sidebar"] & JSXBase.HTMLAttributes<HTMLWtSidebarElement>;
            /**
             * Renders a single signal row inside the sidebar.
             * For **group** signals it shows a group header with an editable alias
             * and recursively renders children as nested `wt-sidebar-item` elements.
             * For **divider** signals it renders a blank header.
             * For all other types it renders the icon, optional bus-size badge,
             * signal name (with scope), and the current value display.
             */
            "wt-sidebar-item": LocalJSX.IntrinsicElements["wt-sidebar-item"] & JSXBase.HTMLAttributes<HTMLWtSidebarItemElement>;
            /**
             * Scrollable, drag-reorderable signal list container.
             * This is a lightweight generic drag-and-drop list used for
             * prototyping reorder behaviour.  The main sidebar (`wt-sidebar`)
             * has its own built-in drag logic that supersedes this component for
             * the primary signal list, but `wt-sidebar-list` is retained as a
             * reusable primitive.
             */
            "wt-sidebar-list": LocalJSX.IntrinsicElements["wt-sidebar-list"] & JSXBase.HTMLAttributes<HTMLWtSidebarListElement>;
            /**
             * Inline property editor for a single signal.
             * Displays a color picker, renderer-type toggle buttons
             * (digital / step / linear), and a format button.
             * Emits `waveformChanged` when any property is modified so the
             * parent can update the canvas.
             */
            "wt-sidebar-prop": LocalJSX.IntrinsicElements["wt-sidebar-prop"] & JSXBase.HTMLAttributes<HTMLWtSidebarPropElement>;
            /**
             * Dropdown menu for selecting the display radix of a signal value.
             * Lists all `Radix` members (bin, oct, hex, unsigned, signed, ascii,
             * utf8, float) and highlights the currently-selected one.
             * Emits `waveformChanged` on selection and `select` to let the
             * parent know a choice was made (so it can close the dropdown).
             */
            "wt-sidebar-radix": LocalJSX.IntrinsicElements["wt-sidebar-radix"] & JSXBase.HTMLAttributes<HTMLWtSidebarRadixElement>;
            "wt-window": LocalJSX.IntrinsicElements["wt-window"] & JSXBase.HTMLAttributes<HTMLWtWindowElement>;
        }
    }
}
