/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppConfig, Signal, SignalDisplay } from "./utils/types";
import { Viewport } from "./components/ot-canvas-nav/ot-canvas-nav";
export { AppConfig, Signal, SignalDisplay } from "./utils/types";
export { Viewport } from "./components/ot-canvas-nav/ot-canvas-nav";
export namespace Components {
    /**
     * Color selection widget.
     * Displays a small color swatch that, when clicked, opens a dropdown
     * with a palette of preset colors and a fill-opacity slider.
     * Emits a `change` event whenever a color or fill value is modified.
     */
    interface ColorPicker {
        /**
          * The currently selected CSS color string.
          * @default 'red'
         */
        "color": string;
        /**
          * Fill opacity (0 = transparent, 1 = fully opaque).
          * @default 0.5
         */
        "fill": number;
        "hide": () => Promise<void>;
        /**
          * Array of CSS color strings to show in the swatch palette.
          * @default DEFAULT_CONFIG.theme.palette
         */
        "palette": string[];
    }
    interface OtApp {
        /**
          * Clear the current VCD data and all signals.
         */
        "clear": () => Promise<void>;
        /**
          * Export current signal list as formatted JSON.
         */
        "export": () => Promise<string>;
        /**
          * Notify the canvas that the underlying file has been modified externally.
         */
        "fileChanged": () => Promise<void>;
        /**
          * Get hierarchy node data from the WASM parser.
         */
        "getNodes": () => Promise<string>;
        /**
          * Import signals from a JSON string (e.g. saved workspace).
         */
        "import": (json: string) => Promise<void>;
        /**
          * Load / apply a new configuration object.
         */
        "loadConfig": (config: AppConfig) => Promise<void>;
        /**
          * Parse a VCD file buffer. Populates signal tree and logs info.
         */
        "parse": (data: any) => Promise<void>;
        /**
          * Parse a binary waveform file (FST, GHW, or binary VCD) using the wellen backend.
         */
        "parseBytes": (data: Uint8Array) => Promise<void>;
        /**
          * Redo a previously undone signal operation.
         */
        "redo": () => Promise<void>;
        /**
          * Force a canvas redraw / resize.
         */
        "redraw": () => Promise<void>;
        /**
          * Undo the last signal operation.
         */
        "undo": () => Promise<void>;
    }
    interface OtCanvas {
        /**
          * Clear the active-signal highlight.
         */
        "clearActive": () => Promise<void>;
        /**
          * Application configuration (keyboard, mouse, display settings).
         */
        "config"?: AppConfig;
        /**
          * Remove one or more signals by id. Accepts Signal objects or numeric ids.
         */
        "delete": (...items: (Signal | number)[]) => Promise<void>;
        /**
          * Whether the backing waveform file has changed on disk.
          * @default false
         */
        "fileChanged": boolean;
        /**
          * Get the time delta between the two cursors.
         */
        "getCursorDelta": () => Promise<number>;
        /**
          * Get position of both cursors.
         */
        "getCursorPositions": () => Promise<{ primary: number; secondary: number; }>;
        /**
          * Rebind keyboard shortcuts after config change.
         */
        "input": () => Promise<void>;
        /**
          * Navigate to the next edge of the active signal.
         */
        "nextEdge": () => Promise<void>;
        /**
          * Navigate to the previous edge of the active signal.
         */
        "prevEdge": () => Promise<void>;
        /**
          * Set the currently-highlighted / active signal.
         */
        "setActiveSignal": (id: number) => Promise<void>;
        /**
          * Map of signal id -> signal metadata, keyed by numeric id.
         */
        "signals": Map<number, Signal> | null;
        /**
          * Toggle between primary and secondary cursor.
         */
        "toggleActiveCursor": () => Promise<void>;
        /**
          * Re-evaluate cursor values without moving it.
         */
        "updateCursor": () => Promise<void>;
    }
    /**
     * Navigation bar displayed above the waveform canvas.
     * Provides zoom controls (in / out / fit), a reload button,
     * a settings button, and a minimap slider showing the current
     * viewport position within the full waveform.
     */
    interface OtCanvasNav {
        /**
          * Whether the backing file has changed on disk (highlights the reload button).
          * @default false
         */
        "fileChanged": boolean;
        /**
          * Position the primary cursor marker at the given percentage (0-100).
         */
        "setPrimaryMarker": (pct: number) => Promise<void>;
        /**
          * Position the secondary cursor marker at the given percentage (0-100).
         */
        "setSecondaryMarker": (pct: number) => Promise<void>;
        /**
          * Update the viewport data and refresh the minimap preview.
         */
        "setViewport": (vp: Viewport) => Promise<void>;
    }
    /**
     * Properties panel shown below the sidebar.
     * Displays and edits shared display properties for the currently
     * selected signal(s): color, fill, renderer mode, endianness, radix,
     * and waveform height.
     */
    interface OtProperties {
        /**
          * The set of currently selected signals whose properties are shown/edited.
          * @default []
         */
        "signals": Signal[];
    }
    /**
     * Modal dialog for browsing and adding VCD signals to the waveform display.
     * Shows a hierarchical module tree on the left and a filterable signal list
     * on the right.  Supports multi-select (ctrl/shift), keyboard navigation,
     * and type-based filtering (wire, reg, logic, etc.).
     */
    interface OtSearch {
        /**
          * Hide the search dialog.
         */
        "hide": () => Promise<void>;
        /**
          * Load a signal dictionary from the parsed VCD file.
         */
        "load": (dict: any[]) => Promise<void>;
        /**
          * Horizontal offset for positioning.
          * @default 0
         */
        "offsetX": number;
        /**
          * Show the search dialog.
         */
        "show": () => Promise<void>;
        /**
          * Toggle the search dialog visibility.
         */
        "toggle": () => Promise<void>;
    }
    /**
     * Settings panel component.
     * Provides tabbed UI for:
     *  - Keyboard shortcut customisation
     *  - Advanced / JSON config editing
     *  - About page (rebranded to OpenTrace)
     * All licensing / activation functionality has been removed.
     */
    interface OtSettings {
        /**
          * The application config object (passed by reference from the host).
          * @default null
         */
        "config": AppConfig | null;
        /**
          * Hide the settings window.
         */
        "hide": () => Promise<void>;
        /**
          * Show the settings window.
         */
        "show": () => Promise<void>;
    }
    /**
     * Main sidebar container for the signal list.
     * Manages:
     *  - Rendering the ordered list of signals via `ot-sidebar-item`.
     *  - Multi-select with Ctrl click, adjacent navigation with arrows.
     *  - Drag-and-drop reordering of signals.
     *  - A footer with "Add Signals" and delete buttons.
     *  - Delegates to `ot-properties` for bulk property editing.
     */
    interface OtSidebar {
        /**
          * Clear all selection state.
         */
        "clearSelection": () => Promise<void>;
        /**
          * Whether the waveform definition file has been fully parsed.
          * @default false
         */
        "defined": boolean;
        /**
          * Whether there was an error loading the file.
          * @default false
         */
        "error": boolean;
        /**
          * Return selected signal IDs and clear the selection classes.
         */
        "getSelected": () => Promise<number[]>;
        /**
          * Move selected signals up or down in the list.
         */
        "moveSelectedSignals": (direction?: number) => Promise<void>;
        /**
          * Recalculate signal positions after layout changes.
         */
        "resize": () => Promise<boolean>;
        /**
          * Select the next or previous adjacent signal.
         */
        "selectAdjacent": (forward?: boolean) => Promise<void>;
        /**
          * Select all signals.
         */
        "selectAll": () => Promise<void>;
        /**
          * @default []
         */
        "signals": Signal[];
        /**
          * Update cursor values for all visible signals.
         */
        "updateCursor": (values: Record<string, string>) => Promise<void>;
    }
    /**
     * Renders a single signal row inside the sidebar.
     * For **group** signals it shows a group header with an editable alias
     * and recursively renders children as nested `ot-sidebar-item` elements.
     * For **divider** signals it renders a blank header.
     * For all other types it renders the icon, optional bus-size badge,
     * signal name (with scope), and the current value display.
     */
    interface OtSidebarItem {
        /**
          * Measure the rendered element and write display.y / display.height back.
         */
        "resizeSignal": () => Promise<void>;
        /**
          * The signal data object to render.
         */
        "signal": Signal;
        /**
          * Current cursor value for this signal (displayed in the radix column).
          * @default ''
         */
        "value": string;
    }
    /**
     * Inline property editor for a single signal.
     * Displays a color picker, renderer-type toggle buttons
     * (digital / step / linear), and a format button.
     * Emits `waveformChanged` when any property is modified so the
     * parent can update the canvas.
     */
    interface OtSidebarProp {
        /**
          * Bit-width of the signal (controls which renderer buttons are shown).
          * @default 0
         */
        "busSize": number;
        /**
          * Display options for the signal being edited.
          * @default {} as SignalDisplay
         */
        "options": SignalDisplay;
    }
    /**
     * Dropdown menu for selecting the display radix of a signal value.
     * Lists all `Radix` members (bin, oct, hex, unsigned, signed, ascii,
     * utf8, float) and highlights the currently-selected one.
     * Emits `waveformChanged` on selection and `select` to let the
     * parent know a choice was made (so it can close the dropdown).
     */
    interface OtSidebarRadix {
        /**
          * Display options (contains `.radix` and `.color`).
          * @default {} as SignalDisplay
         */
        "options": SignalDisplay;
    }
    interface OtWindow {
        /**
          * When true, applies a backdrop blur effect behind the window.
          * @default false
         */
        "backgroundBlur": boolean;
        /**
          * Hide the window.
         */
        "hide": () => Promise<void>;
        /**
          * Show the window.
         */
        "show": () => Promise<void>;
        /**
          * Controls visibility of the modal overlay.
          * @default false
         */
        "visible": boolean;
        /**
          * Title displayed in the gradient title bar. Empty string hides the bar.
          * @default ''
         */
        "windowTitle": string;
    }
}
export interface ColorPickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLColorPickerElement;
}
export interface OtAppCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtAppElement;
}
export interface OtCanvasCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtCanvasElement;
}
export interface OtCanvasNavCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtCanvasNavElement;
}
export interface OtPropertiesCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtPropertiesElement;
}
export interface OtSearchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtSearchElement;
}
export interface OtSettingsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtSettingsElement;
}
export interface OtSidebarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtSidebarElement;
}
export interface OtSidebarItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtSidebarItemElement;
}
export interface OtSidebarPropCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtSidebarPropElement;
}
export interface OtSidebarRadixCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOtSidebarRadixElement;
}
declare global {
    interface HTMLColorPickerElementEventMap {
        "colorChange": { color: string; fill: number };
    }
    /**
     * Color selection widget.
     * Displays a small color swatch that, when clicked, opens a dropdown
     * with a palette of preset colors and a fill-opacity slider.
     * Emits a `change` event whenever a color or fill value is modified.
     */
    interface HTMLColorPickerElement extends Components.ColorPicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLColorPickerElementEventMap>(type: K, listener: (this: HTMLColorPickerElement, ev: ColorPickerCustomEvent<HTMLColorPickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLColorPickerElementEventMap>(type: K, listener: (this: HTMLColorPickerElement, ev: ColorPickerCustomEvent<HTMLColorPickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLColorPickerElement: {
        prototype: HTMLColorPickerElement;
        new (): HTMLColorPickerElement;
    };
    interface HTMLOtAppElementEventMap {
        "vcd-ready": void;
        "vcd-done": void;
        "log": string;
        "file-reload": {};
        "config-save": string;
        "config-reset": {};
        "state-changed": {};
        "config-reload": {};
        "settings-json": {};
        "open-website": {};
    }
    interface HTMLOtAppElement extends Components.OtApp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtAppElementEventMap>(type: K, listener: (this: HTMLOtAppElement, ev: OtAppCustomEvent<HTMLOtAppElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtAppElementEventMap>(type: K, listener: (this: HTMLOtAppElement, ev: OtAppCustomEvent<HTMLOtAppElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtAppElement: {
        prototype: HTMLOtAppElement;
        new (): HTMLOtAppElement;
    };
    interface HTMLOtCanvasElementEventMap {
        "setCursor": Record<string, string>;
        "settings": void;
    }
    interface HTMLOtCanvasElement extends Components.OtCanvas, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtCanvasElementEventMap>(type: K, listener: (this: HTMLOtCanvasElement, ev: OtCanvasCustomEvent<HTMLOtCanvasElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtCanvasElementEventMap>(type: K, listener: (this: HTMLOtCanvasElement, ev: OtCanvasCustomEvent<HTMLOtCanvasElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtCanvasElement: {
        prototype: HTMLOtCanvasElement;
        new (): HTMLOtCanvasElement;
    };
    interface HTMLOtCanvasNavElementEventMap {
        "viewportChange": { cmd: string; value?: number };
        "file-reload": {};
        "settings": {};
    }
    /**
     * Navigation bar displayed above the waveform canvas.
     * Provides zoom controls (in / out / fit), a reload button,
     * a settings button, and a minimap slider showing the current
     * viewport position within the full waveform.
     */
    interface HTMLOtCanvasNavElement extends Components.OtCanvasNav, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtCanvasNavElementEventMap>(type: K, listener: (this: HTMLOtCanvasNavElement, ev: OtCanvasNavCustomEvent<HTMLOtCanvasNavElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtCanvasNavElementEventMap>(type: K, listener: (this: HTMLOtCanvasNavElement, ev: OtCanvasNavCustomEvent<HTMLOtCanvasNavElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtCanvasNavElement: {
        prototype: HTMLOtCanvasNavElement;
        new (): HTMLOtCanvasNavElement;
    };
    interface HTMLOtPropertiesElementEventMap {
        "redraw": { resize: boolean };
    }
    /**
     * Properties panel shown below the sidebar.
     * Displays and edits shared display properties for the currently
     * selected signal(s): color, fill, renderer mode, endianness, radix,
     * and waveform height.
     */
    interface HTMLOtPropertiesElement extends Components.OtProperties, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtPropertiesElementEventMap>(type: K, listener: (this: HTMLOtPropertiesElement, ev: OtPropertiesCustomEvent<HTMLOtPropertiesElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtPropertiesElementEventMap>(type: K, listener: (this: HTMLOtPropertiesElement, ev: OtPropertiesCustomEvent<HTMLOtPropertiesElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtPropertiesElement: {
        prototype: HTMLOtPropertiesElement;
        new (): HTMLOtPropertiesElement;
    };
    interface HTMLOtSearchElementEventMap {
        "add": Signal[];
    }
    /**
     * Modal dialog for browsing and adding VCD signals to the waveform display.
     * Shows a hierarchical module tree on the left and a filterable signal list
     * on the right.  Supports multi-select (ctrl/shift), keyboard navigation,
     * and type-based filtering (wire, reg, logic, etc.).
     */
    interface HTMLOtSearchElement extends Components.OtSearch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtSearchElementEventMap>(type: K, listener: (this: HTMLOtSearchElement, ev: OtSearchCustomEvent<HTMLOtSearchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtSearchElementEventMap>(type: K, listener: (this: HTMLOtSearchElement, ev: OtSearchCustomEvent<HTMLOtSearchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtSearchElement: {
        prototype: HTMLOtSearchElement;
        new (): HTMLOtSearchElement;
    };
    interface HTMLOtSettingsElementEventMap {
        "config-save": string;
        "settings-json": {};
        "config-reload": {};
        "config-reset": {};
    }
    /**
     * Settings panel component.
     * Provides tabbed UI for:
     *  - Keyboard shortcut customisation
     *  - Advanced / JSON config editing
     *  - About page (rebranded to OpenTrace)
     * All licensing / activation functionality has been removed.
     */
    interface HTMLOtSettingsElement extends Components.OtSettings, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtSettingsElementEventMap>(type: K, listener: (this: HTMLOtSettingsElement, ev: OtSettingsCustomEvent<HTMLOtSettingsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtSettingsElementEventMap>(type: K, listener: (this: HTMLOtSettingsElement, ev: OtSettingsCustomEvent<HTMLOtSettingsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtSettingsElement: {
        prototype: HTMLOtSettingsElement;
        new (): HTMLOtSettingsElement;
    };
    interface HTMLOtSidebarElementEventMap {
        "add": void;
        "delete": void;
        "waveformChanged": void;
        "redraw": { resize?: boolean };
        "setActiveSignal": number;
    }
    /**
     * Main sidebar container for the signal list.
     * Manages:
     *  - Rendering the ordered list of signals via `ot-sidebar-item`.
     *  - Multi-select with Ctrl click, adjacent navigation with arrows.
     *  - Drag-and-drop reordering of signals.
     *  - A footer with "Add Signals" and delete buttons.
     *  - Delegates to `ot-properties` for bulk property editing.
     */
    interface HTMLOtSidebarElement extends Components.OtSidebar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtSidebarElementEventMap>(type: K, listener: (this: HTMLOtSidebarElement, ev: OtSidebarCustomEvent<HTMLOtSidebarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtSidebarElementEventMap>(type: K, listener: (this: HTMLOtSidebarElement, ev: OtSidebarCustomEvent<HTMLOtSidebarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtSidebarElement: {
        prototype: HTMLOtSidebarElement;
        new (): HTMLOtSidebarElement;
    };
    interface HTMLOtSidebarItemElementEventMap {
        "resizeSignals": void;
    }
    /**
     * Renders a single signal row inside the sidebar.
     * For **group** signals it shows a group header with an editable alias
     * and recursively renders children as nested `ot-sidebar-item` elements.
     * For **divider** signals it renders a blank header.
     * For all other types it renders the icon, optional bus-size badge,
     * signal name (with scope), and the current value display.
     */
    interface HTMLOtSidebarItemElement extends Components.OtSidebarItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtSidebarItemElementEventMap>(type: K, listener: (this: HTMLOtSidebarItemElement, ev: OtSidebarItemCustomEvent<HTMLOtSidebarItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtSidebarItemElementEventMap>(type: K, listener: (this: HTMLOtSidebarItemElement, ev: OtSidebarItemCustomEvent<HTMLOtSidebarItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtSidebarItemElement: {
        prototype: HTMLOtSidebarItemElement;
        new (): HTMLOtSidebarItemElement;
    };
    interface HTMLOtSidebarPropElementEventMap {
        "waveformChanged": SignalDisplay;
        "resizeSignals": void;
    }
    /**
     * Inline property editor for a single signal.
     * Displays a color picker, renderer-type toggle buttons
     * (digital / step / linear), and a format button.
     * Emits `waveformChanged` when any property is modified so the
     * parent can update the canvas.
     */
    interface HTMLOtSidebarPropElement extends Components.OtSidebarProp, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtSidebarPropElementEventMap>(type: K, listener: (this: HTMLOtSidebarPropElement, ev: OtSidebarPropCustomEvent<HTMLOtSidebarPropElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtSidebarPropElementEventMap>(type: K, listener: (this: HTMLOtSidebarPropElement, ev: OtSidebarPropCustomEvent<HTMLOtSidebarPropElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtSidebarPropElement: {
        prototype: HTMLOtSidebarPropElement;
        new (): HTMLOtSidebarPropElement;
    };
    interface HTMLOtSidebarRadixElementEventMap {
        "waveformChanged": SignalDisplay;
        "radixSelect": void;
        "resizeSignals": void;
    }
    /**
     * Dropdown menu for selecting the display radix of a signal value.
     * Lists all `Radix` members (bin, oct, hex, unsigned, signed, ascii,
     * utf8, float) and highlights the currently-selected one.
     * Emits `waveformChanged` on selection and `select` to let the
     * parent know a choice was made (so it can close the dropdown).
     */
    interface HTMLOtSidebarRadixElement extends Components.OtSidebarRadix, HTMLStencilElement {
        addEventListener<K extends keyof HTMLOtSidebarRadixElementEventMap>(type: K, listener: (this: HTMLOtSidebarRadixElement, ev: OtSidebarRadixCustomEvent<HTMLOtSidebarRadixElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLOtSidebarRadixElementEventMap>(type: K, listener: (this: HTMLOtSidebarRadixElement, ev: OtSidebarRadixCustomEvent<HTMLOtSidebarRadixElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLOtSidebarRadixElement: {
        prototype: HTMLOtSidebarRadixElement;
        new (): HTMLOtSidebarRadixElement;
    };
    interface HTMLOtWindowElement extends Components.OtWindow, HTMLStencilElement {
    }
    var HTMLOtWindowElement: {
        prototype: HTMLOtWindowElement;
        new (): HTMLOtWindowElement;
    };
    interface HTMLElementTagNameMap {
        "color-picker": HTMLColorPickerElement;
        "ot-app": HTMLOtAppElement;
        "ot-canvas": HTMLOtCanvasElement;
        "ot-canvas-nav": HTMLOtCanvasNavElement;
        "ot-properties": HTMLOtPropertiesElement;
        "ot-search": HTMLOtSearchElement;
        "ot-settings": HTMLOtSettingsElement;
        "ot-sidebar": HTMLOtSidebarElement;
        "ot-sidebar-item": HTMLOtSidebarItemElement;
        "ot-sidebar-prop": HTMLOtSidebarPropElement;
        "ot-sidebar-radix": HTMLOtSidebarRadixElement;
        "ot-window": HTMLOtWindowElement;
    }
}
declare namespace LocalJSX {
    /**
     * Color selection widget.
     * Displays a small color swatch that, when clicked, opens a dropdown
     * with a palette of preset colors and a fill-opacity slider.
     * Emits a `change` event whenever a color or fill value is modified.
     */
    interface ColorPicker {
        /**
          * The currently selected CSS color string.
          * @default 'red'
         */
        "color"?: string;
        /**
          * Fill opacity (0 = transparent, 1 = fully opaque).
          * @default 0.5
         */
        "fill"?: number;
        /**
          * Emitted when the user selects a new color or changes the fill.
         */
        "onColorChange"?: (event: ColorPickerCustomEvent<{ color: string; fill: number }>) => void;
        /**
          * Array of CSS color strings to show in the swatch palette.
          * @default DEFAULT_CONFIG.theme.palette
         */
        "palette"?: string[];
    }
    interface OtApp {
        "onConfig-reload"?: (event: OtAppCustomEvent<{}>) => void;
        "onConfig-reset"?: (event: OtAppCustomEvent<{}>) => void;
        "onConfig-save"?: (event: OtAppCustomEvent<string>) => void;
        "onFile-reload"?: (event: OtAppCustomEvent<{}>) => void;
        "onLog"?: (event: OtAppCustomEvent<string>) => void;
        "onOpen-website"?: (event: OtAppCustomEvent<{}>) => void;
        "onSettings-json"?: (event: OtAppCustomEvent<{}>) => void;
        "onState-changed"?: (event: OtAppCustomEvent<{}>) => void;
        "onVcd-done"?: (event: OtAppCustomEvent<void>) => void;
        "onVcd-ready"?: (event: OtAppCustomEvent<void>) => void;
    }
    interface OtCanvas {
        /**
          * Application configuration (keyboard, mouse, display settings).
         */
        "config"?: AppConfig;
        /**
          * Whether the backing waveform file has changed on disk.
          * @default false
         */
        "fileChanged"?: boolean;
        /**
          * Emitted when the cursor moves, carrying the value at the cursor for each signal.
         */
        "onSetCursor"?: (event: OtCanvasCustomEvent<Record<string, string>>) => void;
        /**
          * Emitted when the user requests the settings panel.
         */
        "onSettings"?: (event: OtCanvasCustomEvent<void>) => void;
        /**
          * Map of signal id -> signal metadata, keyed by numeric id.
         */
        "signals": Map<number, Signal> | null;
    }
    /**
     * Navigation bar displayed above the waveform canvas.
     * Provides zoom controls (in / out / fit), a reload button,
     * a settings button, and a minimap slider showing the current
     * viewport position within the full waveform.
     */
    interface OtCanvasNav {
        /**
          * Whether the backing file has changed on disk (highlights the reload button).
          * @default false
         */
        "fileChanged"?: boolean;
        /**
          * Emitted when the user clicks the reload button.
         */
        "onFile-reload"?: (event: OtCanvasNavCustomEvent<{}>) => void;
        /**
          * Emitted when the user clicks the settings button.
         */
        "onSettings"?: (event: OtCanvasNavCustomEvent<{}>) => void;
        /**
          * Emitted when the user requests a viewport change (zoom, goto).
         */
        "onViewportChange"?: (event: OtCanvasNavCustomEvent<{ cmd: string; value?: number }>) => void;
    }
    /**
     * Properties panel shown below the sidebar.
     * Displays and edits shared display properties for the currently
     * selected signal(s): color, fill, renderer mode, endianness, radix,
     * and waveform height.
     */
    interface OtProperties {
        /**
          * Emitted when a property changes, requesting the canvas to redraw.
         */
        "onRedraw"?: (event: OtPropertiesCustomEvent<{ resize: boolean }>) => void;
        /**
          * The set of currently selected signals whose properties are shown/edited.
          * @default []
         */
        "signals"?: Signal[];
    }
    /**
     * Modal dialog for browsing and adding VCD signals to the waveform display.
     * Shows a hierarchical module tree on the left and a filterable signal list
     * on the right.  Supports multi-select (ctrl/shift), keyboard navigation,
     * and type-based filtering (wire, reg, logic, etc.).
     */
    interface OtSearch {
        /**
          * Horizontal offset for positioning.
          * @default 0
         */
        "offsetX"?: number;
        /**
          * Emitted when the user adds selected signals. Detail is the array of Signal objects.
         */
        "onAdd"?: (event: OtSearchCustomEvent<Signal[]>) => void;
    }
    /**
     * Settings panel component.
     * Provides tabbed UI for:
     *  - Keyboard shortcut customisation
     *  - Advanced / JSON config editing
     *  - About page (rebranded to OpenTrace)
     * All licensing / activation functionality has been removed.
     */
    interface OtSettings {
        /**
          * The application config object (passed by reference from the host).
          * @default null
         */
        "config"?: AppConfig | null;
        /**
          * Emitted to request the host to reload config from disk.
         */
        "onConfig-reload"?: (event: OtSettingsCustomEvent<{}>) => void;
        /**
          * Emitted to request the host to reset config to defaults.
         */
        "onConfig-reset"?: (event: OtSettingsCustomEvent<{}>) => void;
        /**
          * Emitted when the user clicks Apply to persist shortcut changes.
         */
        "onConfig-save"?: (event: OtSettingsCustomEvent<string>) => void;
        /**
          * Emitted to request the host to open the JSON settings file.
         */
        "onSettings-json"?: (event: OtSettingsCustomEvent<{}>) => void;
    }
    /**
     * Main sidebar container for the signal list.
     * Manages:
     *  - Rendering the ordered list of signals via `ot-sidebar-item`.
     *  - Multi-select with Ctrl click, adjacent navigation with arrows.
     *  - Drag-and-drop reordering of signals.
     *  - A footer with "Add Signals" and delete buttons.
     *  - Delegates to `ot-properties` for bulk property editing.
     */
    interface OtSidebar {
        /**
          * Whether the waveform definition file has been fully parsed.
          * @default false
         */
        "defined"?: boolean;
        /**
          * Whether there was an error loading the file.
          * @default false
         */
        "error"?: boolean;
        /**
          * Emitted when the user clicks "Add Signals".
         */
        "onAdd"?: (event: OtSidebarCustomEvent<void>) => void;
        /**
          * Emitted when the user clicks the delete button.
         */
        "onDelete"?: (event: OtSidebarCustomEvent<void>) => void;
        /**
          * Emitted when the sidebar layout changes and the canvas needs a redraw.
         */
        "onRedraw"?: (event: OtSidebarCustomEvent<{ resize?: boolean }>) => void;
        /**
          * Emitted to tell the canvas which signal to highlight.
         */
        "onSetActiveSignal"?: (event: OtSidebarCustomEvent<number>) => void;
        /**
          * Emitted when signals are reordered, properties change, etc.
         */
        "onWaveformChanged"?: (event: OtSidebarCustomEvent<void>) => void;
        /**
          * @default []
         */
        "signals"?: Signal[];
    }
    /**
     * Renders a single signal row inside the sidebar.
     * For **group** signals it shows a group header with an editable alias
     * and recursively renders children as nested `ot-sidebar-item` elements.
     * For **divider** signals it renders a blank header.
     * For all other types it renders the icon, optional bus-size badge,
     * signal name (with scope), and the current value display.
     */
    interface OtSidebarItem {
        /**
          * Bubbles up to request a full signal-height recalculation.
         */
        "onResizeSignals"?: (event: OtSidebarItemCustomEvent<void>) => void;
        /**
          * The signal data object to render.
         */
        "signal": Signal;
        /**
          * Current cursor value for this signal (displayed in the radix column).
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Inline property editor for a single signal.
     * Displays a color picker, renderer-type toggle buttons
     * (digital / step / linear), and a format button.
     * Emits `waveformChanged` when any property is modified so the
     * parent can update the canvas.
     */
    interface OtSidebarProp {
        /**
          * Bit-width of the signal (controls which renderer buttons are shown).
          * @default 0
         */
        "busSize"?: number;
        /**
          * Requests a full signal-height recalculation.
         */
        "onResizeSignals"?: (event: OtSidebarPropCustomEvent<void>) => void;
        /**
          * Emitted whenever a display property is changed.
         */
        "onWaveformChanged"?: (event: OtSidebarPropCustomEvent<SignalDisplay>) => void;
        /**
          * Display options for the signal being edited.
          * @default {} as SignalDisplay
         */
        "options"?: SignalDisplay;
    }
    /**
     * Dropdown menu for selecting the display radix of a signal value.
     * Lists all `Radix` members (bin, oct, hex, unsigned, signed, ascii,
     * utf8, float) and highlights the currently-selected one.
     * Emits `waveformChanged` on selection and `select` to let the
     * parent know a choice was made (so it can close the dropdown).
     */
    interface OtSidebarRadix {
        /**
          * Emitted after a radix is selected (used by parent to close the menu).
         */
        "onRadixSelect"?: (event: OtSidebarRadixCustomEvent<void>) => void;
        /**
          * Requests a full signal-height recalculation.
         */
        "onResizeSignals"?: (event: OtSidebarRadixCustomEvent<void>) => void;
        /**
          * Emitted when the radix changes.
         */
        "onWaveformChanged"?: (event: OtSidebarRadixCustomEvent<SignalDisplay>) => void;
        /**
          * Display options (contains `.radix` and `.color`).
          * @default {} as SignalDisplay
         */
        "options"?: SignalDisplay;
    }
    interface OtWindow {
        /**
          * When true, applies a backdrop blur effect behind the window.
          * @default false
         */
        "backgroundBlur"?: boolean;
        /**
          * Controls visibility of the modal overlay.
          * @default false
         */
        "visible"?: boolean;
        /**
          * Title displayed in the gradient title bar. Empty string hides the bar.
          * @default ''
         */
        "windowTitle"?: string;
    }

    interface ColorPickerAttributes {
        "color": string;
        "fill": number;
    }
    interface OtCanvasAttributes {
        "fileChanged": boolean;
    }
    interface OtCanvasNavAttributes {
        "fileChanged": boolean;
    }
    interface OtSearchAttributes {
        "offsetX": number;
    }
    interface OtSidebarAttributes {
        "defined": boolean;
        "error": boolean;
    }
    interface OtSidebarItemAttributes {
        "value": string;
    }
    interface OtSidebarPropAttributes {
        "busSize": number;
    }
    interface OtWindowAttributes {
        "windowTitle": string;
        "backgroundBlur": boolean;
        "visible": boolean;
    }

    interface IntrinsicElements {
        "color-picker": Omit<ColorPicker, keyof ColorPickerAttributes> & { [K in keyof ColorPicker & keyof ColorPickerAttributes]?: ColorPicker[K] } & { [K in keyof ColorPicker & keyof ColorPickerAttributes as `attr:${K}`]?: ColorPickerAttributes[K] } & { [K in keyof ColorPicker & keyof ColorPickerAttributes as `prop:${K}`]?: ColorPicker[K] };
        "ot-app": OtApp;
        "ot-canvas": Omit<OtCanvas, keyof OtCanvasAttributes> & { [K in keyof OtCanvas & keyof OtCanvasAttributes]?: OtCanvas[K] } & { [K in keyof OtCanvas & keyof OtCanvasAttributes as `attr:${K}`]?: OtCanvasAttributes[K] } & { [K in keyof OtCanvas & keyof OtCanvasAttributes as `prop:${K}`]?: OtCanvas[K] };
        "ot-canvas-nav": Omit<OtCanvasNav, keyof OtCanvasNavAttributes> & { [K in keyof OtCanvasNav & keyof OtCanvasNavAttributes]?: OtCanvasNav[K] } & { [K in keyof OtCanvasNav & keyof OtCanvasNavAttributes as `attr:${K}`]?: OtCanvasNavAttributes[K] } & { [K in keyof OtCanvasNav & keyof OtCanvasNavAttributes as `prop:${K}`]?: OtCanvasNav[K] };
        "ot-properties": OtProperties;
        "ot-search": Omit<OtSearch, keyof OtSearchAttributes> & { [K in keyof OtSearch & keyof OtSearchAttributes]?: OtSearch[K] } & { [K in keyof OtSearch & keyof OtSearchAttributes as `attr:${K}`]?: OtSearchAttributes[K] } & { [K in keyof OtSearch & keyof OtSearchAttributes as `prop:${K}`]?: OtSearch[K] };
        "ot-settings": OtSettings;
        "ot-sidebar": Omit<OtSidebar, keyof OtSidebarAttributes> & { [K in keyof OtSidebar & keyof OtSidebarAttributes]?: OtSidebar[K] } & { [K in keyof OtSidebar & keyof OtSidebarAttributes as `attr:${K}`]?: OtSidebarAttributes[K] } & { [K in keyof OtSidebar & keyof OtSidebarAttributes as `prop:${K}`]?: OtSidebar[K] };
        "ot-sidebar-item": Omit<OtSidebarItem, keyof OtSidebarItemAttributes> & { [K in keyof OtSidebarItem & keyof OtSidebarItemAttributes]?: OtSidebarItem[K] } & { [K in keyof OtSidebarItem & keyof OtSidebarItemAttributes as `attr:${K}`]?: OtSidebarItemAttributes[K] } & { [K in keyof OtSidebarItem & keyof OtSidebarItemAttributes as `prop:${K}`]?: OtSidebarItem[K] };
        "ot-sidebar-prop": Omit<OtSidebarProp, keyof OtSidebarPropAttributes> & { [K in keyof OtSidebarProp & keyof OtSidebarPropAttributes]?: OtSidebarProp[K] } & { [K in keyof OtSidebarProp & keyof OtSidebarPropAttributes as `attr:${K}`]?: OtSidebarPropAttributes[K] } & { [K in keyof OtSidebarProp & keyof OtSidebarPropAttributes as `prop:${K}`]?: OtSidebarProp[K] };
        "ot-sidebar-radix": OtSidebarRadix;
        "ot-window": Omit<OtWindow, keyof OtWindowAttributes> & { [K in keyof OtWindow & keyof OtWindowAttributes]?: OtWindow[K] } & { [K in keyof OtWindow & keyof OtWindowAttributes as `attr:${K}`]?: OtWindowAttributes[K] } & { [K in keyof OtWindow & keyof OtWindowAttributes as `prop:${K}`]?: OtWindow[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Color selection widget.
             * Displays a small color swatch that, when clicked, opens a dropdown
             * with a palette of preset colors and a fill-opacity slider.
             * Emits a `change` event whenever a color or fill value is modified.
             */
            "color-picker": LocalJSX.IntrinsicElements["color-picker"] & JSXBase.HTMLAttributes<HTMLColorPickerElement>;
            "ot-app": LocalJSX.IntrinsicElements["ot-app"] & JSXBase.HTMLAttributes<HTMLOtAppElement>;
            "ot-canvas": LocalJSX.IntrinsicElements["ot-canvas"] & JSXBase.HTMLAttributes<HTMLOtCanvasElement>;
            /**
             * Navigation bar displayed above the waveform canvas.
             * Provides zoom controls (in / out / fit), a reload button,
             * a settings button, and a minimap slider showing the current
             * viewport position within the full waveform.
             */
            "ot-canvas-nav": LocalJSX.IntrinsicElements["ot-canvas-nav"] & JSXBase.HTMLAttributes<HTMLOtCanvasNavElement>;
            /**
             * Properties panel shown below the sidebar.
             * Displays and edits shared display properties for the currently
             * selected signal(s): color, fill, renderer mode, endianness, radix,
             * and waveform height.
             */
            "ot-properties": LocalJSX.IntrinsicElements["ot-properties"] & JSXBase.HTMLAttributes<HTMLOtPropertiesElement>;
            /**
             * Modal dialog for browsing and adding VCD signals to the waveform display.
             * Shows a hierarchical module tree on the left and a filterable signal list
             * on the right.  Supports multi-select (ctrl/shift), keyboard navigation,
             * and type-based filtering (wire, reg, logic, etc.).
             */
            "ot-search": LocalJSX.IntrinsicElements["ot-search"] & JSXBase.HTMLAttributes<HTMLOtSearchElement>;
            /**
             * Settings panel component.
             * Provides tabbed UI for:
             *  - Keyboard shortcut customisation
             *  - Advanced / JSON config editing
             *  - About page (rebranded to OpenTrace)
             * All licensing / activation functionality has been removed.
             */
            "ot-settings": LocalJSX.IntrinsicElements["ot-settings"] & JSXBase.HTMLAttributes<HTMLOtSettingsElement>;
            /**
             * Main sidebar container for the signal list.
             * Manages:
             *  - Rendering the ordered list of signals via `ot-sidebar-item`.
             *  - Multi-select with Ctrl click, adjacent navigation with arrows.
             *  - Drag-and-drop reordering of signals.
             *  - A footer with "Add Signals" and delete buttons.
             *  - Delegates to `ot-properties` for bulk property editing.
             */
            "ot-sidebar": LocalJSX.IntrinsicElements["ot-sidebar"] & JSXBase.HTMLAttributes<HTMLOtSidebarElement>;
            /**
             * Renders a single signal row inside the sidebar.
             * For **group** signals it shows a group header with an editable alias
             * and recursively renders children as nested `ot-sidebar-item` elements.
             * For **divider** signals it renders a blank header.
             * For all other types it renders the icon, optional bus-size badge,
             * signal name (with scope), and the current value display.
             */
            "ot-sidebar-item": LocalJSX.IntrinsicElements["ot-sidebar-item"] & JSXBase.HTMLAttributes<HTMLOtSidebarItemElement>;
            /**
             * Inline property editor for a single signal.
             * Displays a color picker, renderer-type toggle buttons
             * (digital / step / linear), and a format button.
             * Emits `waveformChanged` when any property is modified so the
             * parent can update the canvas.
             */
            "ot-sidebar-prop": LocalJSX.IntrinsicElements["ot-sidebar-prop"] & JSXBase.HTMLAttributes<HTMLOtSidebarPropElement>;
            /**
             * Dropdown menu for selecting the display radix of a signal value.
             * Lists all `Radix` members (bin, oct, hex, unsigned, signed, ascii,
             * utf8, float) and highlights the currently-selected one.
             * Emits `waveformChanged` on selection and `select` to let the
             * parent know a choice was made (so it can close the dropdown).
             */
            "ot-sidebar-radix": LocalJSX.IntrinsicElements["ot-sidebar-radix"] & JSXBase.HTMLAttributes<HTMLOtSidebarRadixElement>;
            "ot-window": LocalJSX.IntrinsicElements["ot-window"] & JSXBase.HTMLAttributes<HTMLOtWindowElement>;
        }
    }
}
